import { assetUrl } from "@/lib/supabase-storage";

export const PERSONAL_INFO = {
  name: "Rifqi",
  role: "Information Systems Student",
  location: "Kota Bekasi, Jawa Barat, Indonesia",
  email: "rfqiii1511@gmail.com",

  github: "https://github.com/ki1bot",
  linkedin:
    "https://www.linkedin.com/in/rifq1?utm_source=share_via&utm_content=profile&utm_medium=member_android",
  instagram: "https://www.instagram.com/ki1bot_?igsh=M3o2OTdvb2Q1eXI1",
  spotify:
    "https://open.spotify.com/user/314fig6hgrc2gaq7phryrrmfcp34?si=45c2f5e0cf9e4291",
  youtube: "https://www.youtube.com/@kibot7659",
  tiktok: "https://www.tiktok.com/@kiibott_?_r=1&_t=ZS-96Aalc9CrbQ",

  profileImage: assetUrl("assets/Rifqii.png"),
  description:
    "Saya membangun website modern, responsif, dan terstruktur menggunakan React, Next.js, Tailwind CSS, Shadcn, dan Supabase.",
};

export const TECH_STACK = [
  { name: "HTML", icon: "/img/techstack/html.svg" },
  { name: "CSS", icon: "/img/techstack/css.svg" },
  { name: "JavaScript", icon: "/img/techstack/javascript.svg" },
  { name: "TypeScript", icon: "/img/techstack/typescript.png" },
  { name: "Tailwind CSS", icon: "/img/techstack/tailwind.svg" },
  { name: "Bootstrap", icon: "/img/techstack/bootstrap.svg" },
  { name: "Node.JS", icon: "/img/techstack/nodejs.svg" },
  { name: "Vite", icon: "/img/techstack/vite.svg" },
  { name: "React", icon: "/img/techstack/reactjs.svg" },
  { name: "Angular", icon: "/img/techstack/angular.png" },
  { name: "Vue", icon: "/img/techstack/vue.png" },
  { name: "Nuxt", icon: "/img/techstack/nuxtjs.png" },
  { name: "svelte", icon: "/img/techstack/svelte.png" },
  { name: "Next.JS", icon: "/img/techstack/nextjs.png" },
  { name: "Nest.JS", icon: "/img/techstack/nestjs.png" },
  { name: "Express.JS", icon: "/img/techstack/expressjs.png" },
  { name: "Inertia.JS", icon: "/img/techstack/inertiajs.png" },
  { name: "PHP", icon: "/img/techstack/php.png" },
  { name: "Code Igniter", icon: "/img/techstack/codeigniter.png" },
  { name: "Laravel", icon: "/img/techstack/laravel.png" },
  { name: "Java", icon: "/img/techstack/java.png" },
  { name: "Dart", icon: "/img/techstack/dart.png" },
  { name: "Flutter", icon: "/img/techstack/flutter.png" },
  { name: "Golang", icon: "/img/techstack/golang.png" },
  { name: "Python", icon: "/img/techstack/python.png" },
  { name: "C", icon: "/img/techstack/c.png" },
  { name: "C++", icon: "/img/techstack/c++.png" },
  { name: "Firebase", icon: "/img/techstack/firebase.svg" },
  { name: "Supabase", icon: "/img/techstack/supabase.png" },
  { name: "MySQL", icon: "/img/techstack/mysql.png" },
  { name: "PostgreSQL", icon: "/img/techstack/postgresql.png" },
  { name: "MongoDB", icon: "/img/techstack/mongodb.png" },
  { name: "Prisma", icon: "/img/techstack/prismaorm.png" },
  { name: "Docker", icon: "/img/techstack/docker.png" },
  { name: "Vercel", icon: "/img/techstack/vercel.svg" },
  { name: "Linux", icon: "/img/techstack/linux.png" },
];

export const FALLBACK_PROJECTS = [
  {
    id: 1,
    title: "Sistem Marketplace Broker",
    description:
      "Dashboard sistem marketplace broker yang dibangun menggunakan Laravel 12 sebagai backend, ReactJS sebagai frontend, dan MySQL sebagai database. Sistem ini digunakan untuk mengelola broker, seller, buyer, produk, transaksi, negosiasi, komisi, dan riwayat transaksi dalam satu tampilan modern.",
    img: assetUrl("projects/MarketPlaceBroker.png"),
    link: "https://sistemmarketplacebroker.page.gd/",
    github: "https://github.com/ki1bot/sistem-marketplace-broker.git",
    features: [
      "Frontend menggunakan ReactJS, Backend menggunakan Laravel 12 dan Database menggunakan MySQL",
      "Dashboard utama dan Manajemen broker",
      "Manajemen seller, buyer dan Data produk marketplace",
      "Transaksi, Negosiasi dan Riwayat transaksi",
      "Komisi broker, Visualisasi grafik produk dan status transaksi",
    ],
    tech_stack: [
      "Laravel 12",
      "ReactJS",
      "MySQL",
      "JavaScript",
      "Tailwind CSS",
    ],
    is_published: true,
    order_index: 1,
  },
  {
    id: 2,
    title: "Azzahra Perwira",
    description:
      "Website profil dan sistem pengelolaan konten untuk Yayasan Azzahra Perwira. Website ini menampilkan informasi yayasan, profil lembaga, tenaga pengajar, unit KB/TK, TPQ, daycare, program lansia, berita, kegiatan, brosur, dan informasi kontak. Administrator dapat mengelola teks, gambar, dokumen PDF, urutan tampilan, serta status konten melalui dashboard admin tanpa harus mengubah kode website secara langsung.",
    img: assetUrl("projects/adminUiYayasan.png"),
    link: "https://azzahra-perwira.xo.je/",
    github: "https://github.com/ki1bot/azzahraperwira.git",
    features: [
      "Halaman publik yang mencakup Beranda, Profil Yayasan, Tenaga Pengajar, Unit KB/TK, Unit TPQ, Unit Daycare, Unit Lansia, serta Informasi dan Berita",
      "Dashboard administrator untuk mengelola seluruh konten website dari satu panel",
      "Sistem login admin berbasis session dengan pembatasan akses menggunakan filter autentikasi",
      "Pengelolaan teks, judul, gambar, dokumen, urutan tampilan, dan status aktif atau nonaktif pada setiap konten",
      "Manajemen data tenaga pengajar beserta foto, kategori, pendidikan, urutan, dan status publikasi",
      "Pengelolaan berita dan informasi dinamis yang memiliki halaman detail berdasarkan kode konten",
      "Upload gambar JPG, JPEG, PNG, dan WebP dengan ukuran maksimal 2 MB",
      "Upload dokumen brosur dalam format PDF dengan ukuran maksimal 10 MB",
      "Penghapusan otomatis terhadap file gambar atau dokumen lama ketika media diperbarui atau konten dihapus",
      "Perlindungan struktur utama halaman dengan membatasi konten tetap agar tidak dapat dihapus sembarangan",
      "Pengelolaan footer yang mencakup identitas yayasan, alamat, WhatsApp, Instagram, TikTok, dan informasi hak cipta",
      "Fitur ubah password dan logout administrator",
      "Tampilan responsif untuk halaman publik dan dashboard admin serta dukungan tema terang dan gelap pada panel administrator",
    ],
    tech_stack: [
      "PHP",
      "CodeIgniter 4",
      "MySQL",
      "Tailwind CSS",
      "Alpine.js",
      "JavaScript",
      "Composer",
    ],
    is_published: true,
    order_index: 2,
  },
  {
    id: 3,
    title: "QR Code Generator",
    description:
      "Aplikasi web generate QR Code yang dibuat menggunakan React, TypeScript, Vite, Tailwind CSS, dan qrcode.react. Project ini mendukung pembuatan QR Code untuk URL, domain, Gmail, WhatsApp, telepon, SMS, dan teks biasa. Aplikasi juga dilengkapi fitur tema terang dan gelap, custom warna QR Code, preview real-time, copy target output, serta download QR Code dalam format PNG.",
    img: assetUrl("projects/ProjectQrcode.png"),
    link: "https://generate-qrcode-one.vercel.app/",
    github: "https://github.com/ki1bot/generate-qrcode.git",
    features: [
      "Generate QR Code secara real-time dari input user",
      "Mendukung URL, domain, Gmail, WhatsApp, telepon, SMS, dan teks biasa",
      "Teks biasa otomatis diarahkan ke halaman browser yang menampilkan teks tersebut",
      "Custom warna QR Code dan warna background QR Code",
      "Fitur download QR Code sebagai PNG dan copy target output",
      "Tema terang dan tema gelap dengan tombol icon sun dan moon",
      "Responsive untuk desktop dan mobile",
    ],
    tech_stack: [
      "Vite",
      "React",
      "JavaScript",
      "TypeScript",
      "Tailwind CSS",
      "qrcode.react",
    ],
    is_published: true,
    order_index: 3,
  },
  {
    id: 4,
    title: "Generate Website To PDF",
    description:
      "Website yang membantu pengguna mengubah halaman website menjadi file PDF dengan mudah. Pengguna cukup memasukkan alamat website, menentukan judul, nama file, dan jumlah halaman yang ingin dibuat.",
    img: assetUrl("projects/GeneratePDF.png"),
    link: "https://pdf-generate-nu.vercel.app/",
    github: "https://github.com/ki1bot/pdf-generate.git",
    features: [
      "Mengubah halaman website menjadi file PDF",
      "Menentukan judul yang tampil pada PDF",
      "Mengatur nama file PDF sesuai kebutuhan",
      "Membatasi jumlah halaman yang ingin dibuat",
      "Menampilkan alamat website dan nomor halaman pada PDF",
      "Mengunduh file PDF secara otomatis setelah selesai dibuat",
    ],
    tech_stack: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Express.js",
      "Playwright",
      "pdf-lib",
    ],
    is_published: true,
    order_index: 4,
  },
  {
    id: 5,
    title: "Pelayanan Jasa AC",
    description:
      "Website layanan jasa AC berbasis Laravel untuk mengelola layanan, pemesanan, detail pesanan, pembayaran, autentikasi pelanggan, serta panel admin untuk memproses status pesanan.",
    img: assetUrl("projects/PelayananJasaAc.png"),
    link: "https://pelayananjasaac.rf.gd/",
    github: "https://github.com/ki1bot/pelayananjasaac.git",
    pdf: assetUrl("projects/TugasAlgo2APelayananJasaAc.pdf"),
    features: [
      "Halaman beranda dan daftar layanan jasa AC",
      "Registrasi dan login pelanggan",
      "Pembuatan pesanan layanan oleh pelanggan",
      "Pengelolaan detail pesanan seperti layanan, merk AC, lokasi, dan tarif jarak",
      "Fitur pembayaran untuk pesanan pelanggan",
      "Panel admin untuk melihat dan memproses pesanan",
      "Manajemen status pesanan dari proses sampai selesai",
    ],
    tech_stack: ["Laravel", "PHP", "Blade", "Tailwind CSS", "Vite", "MySQL"],
    is_published: true,
    order_index: 5,
  },
  {
    id: 6,
    title: "3KA28",
    description: "Coming Soon",
    img: assetUrl("projects/ComingSoon.png"),
    link: "https://3ka28.vercel.app/",
    github: "https://github.com/ki1bot/3KA28.git",
    features: ["", "", "", "", "", "", ""],
    tech_stack: ["", "", "", "", "", ""],
    is_published: true,
    order_index: 6,
  },
  {
    id: 7,
    title: "The Flea Defender",
    description:
      "The Flea Defender adalah game RPG survival desktop berbasis Java yang mengajak pemain bertahan hidup sebagai Defender selama 300 detik dari serangan Flea. Flea muncul secara berkala dengan tingkat kekuatan, damage, dan reward RP yang berbeda. Pemain dapat menyerang, bertahan, latihan untuk memulihkan HP, membeli vitamin menggunakan RP, serta melewati waktu untuk mempercepat permainan. Game ini dilengkapi sistem HP dan RP, animasi sprite, sound effect, log permainan, progress status, serta kondisi menang dan kalah.",
    img: assetUrl("projects/flea-defender.png"),
    link: "/games/The%20Flea%20Defender-1.0.0.exe",
    github: "https://github.com/ki1bot/The-Flea-Defender.git",
    features: [
      "Game RPG survival desktop dengan tampilan GUI berbasis Java Swing",
      "Pemain harus menjaga Defender tetap hidup sampai waktu permainan mencapai 300 detik",
      "Sistem HP dan Resource Points yang digunakan selama proses bertahan hidup",
      "Flea muncul setiap 10 detik dan menyerang Defender secara otomatis selama masih aktif",
      "Tiga tipe Flea dengan HP, damage, dan reward RP yang berbeda serta dipilih secara acak",
      "Sistem pertarungan dengan damage acak, self-damage pada Defender, dan reward RP setelah Flea dikalahkan",
      "Fitur latihan untuk memulihkan HP dengan sistem cooldown agar tidak dapat digunakan terus-menerus",
      "Fitur vitamin yang dapat dibeli menggunakan RP untuk memulihkan HP Defender",
      "Fitur bertahan atau guard untuk mengurangi damage dari serangan Flea berikutnya",
      "Fitur melewati waktu 10 detik, Start dan Stop Game, lanjutkan permainan, restart, serta keluar dari game",
      "Animasi Defender dan Flea menggunakan sprite sheet untuk berbagai kondisi selama permainan",
      "Sound effect untuk mendukung animasi dan aksi permainan dengan kontrol suara ON dan OFF",
      "Panel status untuk menampilkan HP, RP, waktu permainan, kondisi Flea, dan status guard",
      "Log permainan yang mencatat spawn Flea, serangan, damage, penggunaan item, serta aktivitas pemain",
      "Ringkasan akhir permainan yang menampilkan hasil menang atau kalah, waktu akhir, sisa HP, total RP, dan jumlah Flea yang dikalahkan",
    ],
    tech_stack: [
      "Java",
      "Java Swing",
      "Java AWT",
      "Java Sound API",
      "Object Oriented Programming",
      "Sprite Sheet Animation",
      "Timer-based Game Loop",
    ],
    is_published: true,
    order_index: 7,
  },
  {
    id: 8,
    title: "Debugging Pemrograman",
    description:
      "Platform latihan debugging interaktif yang membantu pengguna belajar menemukan, memahami, dan memperbaiki kesalahan pada kode program. Setiap tantangan mengajak pengguna menentukan bagian kode yang bermasalah, memperbaikinya melalui code editor, menjalankan hasil perbaikan, lalu menjelaskan penyebab bug yang ditemukan. Tersedia 64 tantangan dari delapan bahasa pemrograman dengan tingkat kesulitan yang berbeda, dilengkapi hint, sistem penilaian, riwayat pengerjaan, progres, poin, dan leaderboard untuk membuat proses belajar debugging lebih terarah.",
    img: assetUrl("projects/DebuggingPemrograman.png"),
    link: "https://debugging-pemrograman.up.railway.app/",
    github: "https://github.com/ki1bot/debugging-pemrograman.git",
    features: [
      "Registrasi dan login pengguna, reset password, verifikasi email, pengelolaan profil dan password, serta fitur untuk menghapus akun",
      "Menyediakan 64 tantangan debugging untuk bahasa C, C++, Go, Java, JavaScript, PHP, Python, dan SQL",
      "Tantangan dibagi ke dalam tingkat kesulitan mudah, menengah, dan sulit dengan poin dasar yang berbeda",
      "Pencarian dan filter tantangan berdasarkan judul, deskripsi, bahasa pemrograman, dan tingkat kesulitan",
      "Alur latihan yang mengharuskan pengguna menentukan baris yang bermasalah, memperbaiki kode, menguji hasil perbaikan, dan menjelaskan penyebab bug",
      "Code editor berbasis CodeMirror dengan syntax highlighting yang menyesuaikan bahasa pemrograman pada setiap tantangan",
      "Menjalankan dan menguji kode melalui Judge0 dengan dukungan input, output, compile error, status eksekusi, waktu proses, dan penggunaan memori",
      "Sistem penilaian berdasarkan ketepatan lokasi bug, hasil perbaikan kode, dan pemahaman pengguna saat menjelaskan penyebab kesalahan",
      "Hint yang dapat dibuka secara bertahap dengan pengurangan skor untuk mendorong pengguna mencoba menyelesaikan masalah secara mandiri",
      "Pembahasan, solusi utama, dan alternatif solusi yang dapat dipelajari setelah tantangan berhasil diselesaikan",
      "Penyimpanan riwayat pengerjaan, jumlah percobaan, skor terbaik, total poin, dan progres penyelesaian tantangan",
      "Leaderboard untuk membandingkan perolehan poin dan progres antar pengguna",
      "Dashboard pengguna untuk melihat perkembangan latihan dan aktivitas debugging yang telah dikerjakan",
      "Dashboard administrator untuk mengelola kategori bahasa, tingkat kesulitan, tantangan, hint, solusi, pengguna, submission, dan statistik aplikasi",
    ],
    tech_stack: [
      "PHP",
      "Laravel",
      "Inertia.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "PostgreSQL",
      "Vite",
      "CodeMirror",
      "Judge0",
      "Recharts",
      "shadcn",
      "Lucide React",
      "Resend",
    ],
    is_published: true,
    order_index: 8,
  },
  {
    id: 9,
    title: "Asisten Akademik",
    description:
      "KampusHub adalah aplikasi pendamping akademik yang membantu mahasiswa mengatur aktivitas perkuliahan dalam satu tempat. Pengguna dapat mencatat semester dan mata kuliah, menyusun jadwal kuliah, mengelola tugas dan ujian, mencatat presensi serta nilai, hingga melihat perkembangan akademik melalui dashboard. Sistem juga dilengkapi autentikasi berbasis JWT, pengelolaan sesi perangkat, notifikasi, perhitungan IP semester, dan statistik penyelesaian tugas. Project dikembangkan dalam arsitektur monorepo dengan aplikasi web berbasis Next.js, backend NestJS dan PostgreSQL, serta aplikasi mobile menggunakan Expo dan React Native.",
    img: assetUrl("projects/AsistenAkademik.png"),
    link: "",
    github: "https://github.com/ki1bot/asisten-akademik.git",
    features: [
      "Registrasi dan login dengan autentikasi JWT serta access token dan refresh token",
      "Pengelolaan sesi login pada beberapa perangkat, termasuk melihat dan menghentikan sesi tertentu atau seluruh sesi",
      "Verifikasi email serta alur lupa dan reset password menggunakan token yang memiliki masa berlaku",
      "Penyimpanan profil mahasiswa yang mencakup nama, NPM, universitas, fakultas, jurusan, dan zona waktu",
      "Pengelolaan semester berdasarkan tahun akademik, semester ganjil atau genap, periode perkuliahan, dan semester aktif",
      "Pengelolaan mata kuliah lengkap dengan kode, jumlah SKS, dosen, ruang kelas, warna, dan catatan",
      "Penyusunan jadwal kuliah berdasarkan hari, waktu, ruang, serta jenis perkuliahan offline, online, atau hybrid",
      "Pengelolaan tugas berdasarkan mata kuliah, deadline, prioritas, status pengerjaan, pengingat, dan lampiran",
      "Pembaruan otomatis status tugas yang telah melewati deadline menjadi terlambat",
      "Pengelolaan jadwal UTS, UAS, kuis, praktikum, presentasi, dan sidang beserta waktu dan lokasi pelaksanaan",
      "Pencatatan presensi mahasiswa dengan status hadir, izin, sakit, tidak hadir, dibatalkan, atau kelas pengganti",
      "Pengelolaan nilai akhir dan komponen penilaian seperti tugas, kuis, UTS, dan UAS dengan bobot masing-masing",
      "Perhitungan otomatis nilai akhir berbobot, nilai huruf, bobot mutu, total SKS, jumlah mutu, dan IP semester",
      "Notifikasi untuk aktivitas akademik seperti tugas, jadwal, ujian, presensi, nilai, dan informasi sistem",
      "Dashboard akademik yang merangkum semester aktif, jadwal hari ini, tugas mendatang dan terlambat, ujian, presensi, nilai, serta notifikasi",
      "Statistik produktivitas berdasarkan jumlah tugas, tugas yang telah selesai, dan persentase penyelesaian",
      "Aplikasi web responsif menggunakan Next.js serta aplikasi mobile menggunakan Expo dan React Native",
      "Arsitektur monorepo dengan kontrak tipe, validasi data, dan API client yang digunakan bersama oleh backend, web, dan mobile",
    ],
    tech_stack: [
      "TypeScript",
      "Next.JS",
      "React",
      "Tailwind CSS",
      "Nest.JS",
      "Prisma",
      "PostgreSQL",
      "Argon2",
      "Swagger",
      "TanStack Query",
      "Zod",
      "Axios",
      "Zustand",
      "Recharts",
      "Lucide React",
      "Expo 54",
      "React Native",
    ],
    is_published: true,
    order_index: 9,
  },
  {
    id: 10,
    title: "SkillPath AI",
    description:
      "Platform pembelajaran dan perencanaan karier yang membantu mahasiswa menentukan target karier, mengukur kemampuan awal, mengetahui keterampilan yang masih perlu dikembangkan, dan mengikuti jalur belajar yang lebih terarah. SkillPath AI menyediakan assessment, analisis skill gap, roadmap pembelajaran, materi dan evaluasi, rekomendasi proyek portofolio, pelacakan progres, serta insight berbasis AI untuk membantu pengguna memahami perkembangan belajar dan menentukan langkah berikutnya.",
    img: assetUrl("projects/SkillPathAI.png"),
    link: "https://skillpath-ai.my.id/",
    github: "https://github.com/ki1bot/skillpath-ai.git",
    features: [
      "Menentukan target karier dan preferensi belajar melalui proses onboarding",
      "Assessment kemampuan awal untuk mengukur kesiapan pengguna terhadap karier yang dipilih",
      "Analisis skill gap untuk melihat kemampuan yang sudah dikuasai dan keterampilan yang masih perlu dikembangkan",
      "Roadmap pembelajaran personal yang berisi materi, latihan, evaluasi, dan progres belajar",
      "Rekomendasi proyek portofolio berdasarkan kebutuhan skill dan tingkat kesiapan pengguna",
      "Pelacakan progres belajar, waktu belajar, hasil evaluasi, dan perkembangan kesiapan karier",
      "Insight berbasis AI untuk memberikan rangkuman perkembangan, saran belajar, variasi latihan, dan feedback proyek",
      "Dashboard administrator untuk mengelola karier, skill, assessment, materi pembelajaran, proyek, feedback, dan pengguna",
    ],
    tech_stack: [
      "PHP",
      "Laravel",
      "Inertia.JS",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "PostgreSQL",
      "Google Gemini API",
      "OpenRouter API",
      "Resend",
      "Vite",
      "Vercel",
    ],
    is_published: true,
    order_index: 10,
  },
];

export const FALLBACK_CERTIFICATES = [
  {
    id: 1,
    title: "Dicoding Certificate 1",
    img: assetUrl("sertifikat/dicoding1.png"),
    pdf_url: assetUrl("sertifikat/dicoding1.pdf"),
    type: "pdf",
    order_index: 1,
  },
  {
    id: 2,
    title: "Dicoding Certificate 2",
    img: assetUrl("sertifikat/dicoding2.png"),
    pdf_url: assetUrl("sertifikat/dicoding2.pdf"),
    type: "pdf",
    order_index: 2,
  },
  {
    id: 3,
    title: "Dicoding Certificate 3",
    img: assetUrl("sertifikat/dicoding3.png"),
    pdf_url: assetUrl("sertifikat/dicoding3.pdf"),
    type: "pdf",
    order_index: 3,
  },
  {
    id: 4,
    title: "Dicoding Certificate 4",
    img: assetUrl("sertifikat/dicoding4.png"),
    pdf_url: assetUrl("sertifikat/dicoding4.pdf"),
    type: "pdf",
    order_index: 4,
  },
  {
    id: 5,
    title: "Dicoding Certificate 5",
    img: assetUrl("sertifikat/dicoding5.png"),
    pdf_url: assetUrl("sertifikat/dicoding5.pdf"),
    type: "pdf",
    order_index: 5,
  },
  {
    id: 6,
    title: "Dicoding Certificate 6",
    img: assetUrl("sertifikat/dicoding6.png"),
    pdf_url: assetUrl("sertifikat/dicoding6.pdf"),
    type: "pdf",
    order_index: 6,
  },
  {
    id: 7,
    title: "Dicoding Certificate 7",
    img: assetUrl("sertifikat/dicoding7.png"),
    pdf_url: assetUrl("sertifikat/dicoding7.pdf"),
    type: "pdf",
    order_index: 7,
  },
  {
    id: 8,
    title: "Dicoding Certificate 8",
    img: assetUrl("sertifikat/dicoding8.png"),
    pdf_url: assetUrl("sertifikat/dicoding8.pdf"),
    type: "pdf",
    order_index: 8,
  },
  {
    id: 9,
    title: "Dicoding Certificate 9",
    img: assetUrl("sertifikat/dicoding9.png"),
    pdf_url: assetUrl("sertifikat/dicoding9.pdf"),
    type: "pdf",
    order_index: 9,
  },
  {
    id: 10,
    title: "RevoU Certificate Data Analytics",
    img: assetUrl("sertifikat/RevoU-DataAnalytics.png"),
    pdf_url: assetUrl("sertifikat/RevoU-DataAnalytics.pdf"),
    type: "pdf",
    order_index: 10,
  },
  {
    id: 11,
    title: "RevoU Certificate Software Engineering",
    img: assetUrl("sertifikat/RevoU-SoftwareEngineering.png"),
    pdf_url: assetUrl("sertifikat/RevoU-SoftwareEngineering.pdf"),
    type: "pdf",
    order_index: 11,
  },
  {
    id: 12,
    title: "Sertifikat LSP Semester 1",
    img: assetUrl("sertifikat/sertifikatlsp-semester1.png"),
    pdf_url: assetUrl("sertifikat/sertifikatlsp-semester1.pdf"),
    type: "pdf",
    order_index: 12,
  },
  {
    id: 13,
    title: "Sertifikat LSP Semester 2",
    img: assetUrl("sertifikat/sertifikatlsp-semester2.png"),
    pdf_url: assetUrl("sertifikat/sertifikatlsp-semester2.pdf"),
    type: "pdf",
    order_index: 13,
  },
  {
    id: 14,
    title: "Sertifikat Kompetensi",
    img: assetUrl("sertifikat/SertifikatKompetensi.png"),
    pdf_url: assetUrl("sertifikat/SertifikatKompetensi.pdf"),
    type: "pdf",
    order_index: 14,
  },
];

export const FALLBACK_COMMENTS = [
  {
    id: "fallback-pinned-comment",
    user_name: "Rifqi",
    content: "Halo, terima kasih sudah mampir ke portofolio saya.",
    profile_image: assetUrl("assets/rifqi.jpg"),
    is_pinned: true,
    created_at: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "fallback-guest-comment",
    user_name: "Faris",
    content: "Portofolionya rapi dan bagus banget.",
    profile_image: assetUrl("screen/default-avatar.jpg"),
    is_pinned: false,
    created_at: "2026-01-01T00:00:00.000Z",
  },
];
